### ISSUE TITLE
how to update the value

### ISSUE THREAD

**Issue by gevikv** [BoD/android-contentprovider-generator#101]
how can i update only one row instead of all?

PhoneSelection where=new PhoneSelection() ;
        where.name(name);
        where.uri();
        PhoneContentValues values =new PhoneContentValues() ;

        PhoneCursor cursor = where .query(context .getContentResolver());
       // ContentUris.withAppendedId(PhoneColumns.CONTENT_URI,)
        while(cursor.moveToNext()){
             smsCount= cursor.getSmsCount();
            // id=

          }
       
        values .putSmsCount(smsCount) ;
       context.getContentResolver().update(where.uri(),values.values(),null,null);

thanks

**Comment by BoD** [comment]
Hi. 
To select only one row for which you know the id, simply use the id(long) method on the Selection object.
