### ISSUE TITLE
FEATURE REQUEST: Support for SQL Views

### ISSUE THREAD

**Issue by dennyh89** [BoD/android-contentprovider-generator#32]
Hi again.
Another topic i recently came across is the support for SQL Views. I need to define a View to easily merge/Join some tables for simple usage in Lists with a CursorAdapter. Therefore i had to change the genrated classes and i think it would be possible to support Views out of the box.

What we need to use a View:
-a Type property for each <entityname>.json file indicating if this is a table or a view
-<ViewName>Selection
-<ViewName>Cursor
-<ViewName>Columns
-SQL_CREATE -> i currently added it in the OpenHelperCallbacks class, but i think it would be nicer to add the views directly in the DatabaseHelper, e.g. with defining a method:
public String getStatementFor<ViewName> in the OpenHelperCallbacks Interface/class
-additional URI for the View and the appropriate Mappings in the Contentprovider itself, alternatively the possibility to define and Extension class to add this kind of URIs

Would be nice to discuss it with you.
Regards.

**Comment by jjkavalam** [comment]
Hi @BoD, @dennyh89, if the support for SQL VIEW has not made its way yet, I will be happy to create a PR.

**Comment by BoD** [comment]
To be honest... Now that Room has been released, my motivation to continue to maintain this tool is very low.  It looks to me that `ContentProvider`s have been unofficially deprecated.

I will probably make this official on the README.

**Comment by jjkavalam** [comment]
@BoD I really appreciate. Just checked out room and it's amazing! 

Only concern if it's available to older Android versions. If not a switch over from content providers may not be possible yet ?
