### ISSUE TITLE
Ability to not have an "id" (primary key) column at all

### ISSUE THREAD

**Issue by druidamix** [BoD/android-contentprovider-generator#56]
HI,

Sqlite documentation says:The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. It is usually not needed.

And sometime I don't need it?

Can you add an extra option in the json template.

Thanks.

**Comment by robUx4** [comment]
To be useful, a ContentProvider needs an `"_id"` field. But it could be possible to alias another Long field in the template to act as the `_id`. And thus being marked as the `PRIMARY KEY` in the database creation.

**Comment by BoD** [comment]
#60 fixed this but to go a bit further, it would be nice to have the ability to not have an "id" (primary key) column at all...  For instance, "join tables" probably don't need this.

**Comment by BoD** [comment]
Yeah in the end I don't think this micro optimization is worth the extra time and code. Closing it for now.
