### ISSUE TITLE
Generate the code with @Nullable and @NonNull annotations

### ISSUE THREAD

**Issue by ansman** [BoD/android-contentprovider-generator#64]
It would be awesome if the generated code used annotation for things can can and cannot be null.

That way we would get warnings in Android Studio.

**Comment by BoD** [comment]
This is actually already implemented, but not yet released. You can use it today by closing the repo and building it. You can also wait a bit as I intend to publish a release this weekend ;-)

**Comment by BoD** [comment]
And I meant cloning, not closing.

**Comment by ansman** [comment]
Awesome! This library is kick ass :)

**Comment by BoD** [comment]
Thanks :)  The week end is almost over, and I couldn't find the time to make a new release (I still have a few PR to merge).  I will probably release it during week.
