### ISSUE TITLE
 INTEGER PRIMARY KEY<#if field.isAutoIncrement> AUTOINCREMENT</#if> in a ftl

### ISSUE THREAD

**Issue by druidamix** [BoD/android-contentprovider-generator#74]
Hi,

I have seen this conditional in sqliteopenhelper.ftl:
 INTEGER PRIMARY KEY<#if field.isAutoIncrement> AUTOINCREMENT</#if> 

It means will you put a neu parameter autoincrement in the jsons to enable or disable autoincrement?

Cheer.s

**Comment by BoD** [comment]
Sorry, there are no plans for this currently.
