### ISSUE TITLE
String equality called with equal signs

### ISSUE THREAD

**Issue by ansman** [BoD/android-contentprovider-generator#77]
The columns class for a table uses `==` to check string equality in `hasColumns`, is this intentional because it would seem risky to do this if the content provider will be used in a cross process environment.

**Comment by BoD** [comment]
It was done this way because you are supposed to always use the constants defined above.

**Comment by ansman** [comment]
Well, in a multi process environment this isn't possible.

**Comment by BoD** [comment]
This is interesting, can you tell me more about what you are doing?

**Comment by ansman** [comment]
We would like to expose our content provider to the outside so that other apps may access it.

**Comment by BoD** [comment]
I see.  I didn't think of that case, and I think you are absolutely right, it will be a problem with the ==.
I will fix it asap and make a new release (PR welcome if you want accelerate the process a bit :) ).

**Comment by ansman** [comment]
I'll make a pull request then :)
Thanks!
