### ISSUE TITLE
Add setCursor to AbstractCursor to prevent extra initialization of model Cursors

### ISSUE THREAD

**Issue by R4md4c** [BoD/android-contentprovider-generator#82]
Hello, 

I have a code that does something like this
```
cursor.moveToFirst();
do {
      UserCursor userCursor = new UserCursor(cursor);
      if (userCursor.getIsRegistered() != null && !userCursor.getIsRegistered()) {
               // do Something
       }
} while (cursor.moveToNext());
```
Instead of creating a new UserCursor each time, why don't we add a setCursor method and reuse the object instead of creating new one, I think that would save memory, right ?

**Comment by sgueniot** [comment]
Hello,
Do move to next on userCursor object instead of data.

Le mar. 7 avr. 2015 12:43, Ahmed I. Khalil <notifications@github.com> a
écrit :

**Comment by R4md4c** [comment]
Hi sgueniot,

Thanks for pointing this out, you are right. It will work this way.

I'll close this issue.
