### ISSUE TITLE
Not qualified columns when projection is null (relevant again)

### ISSUE THREAD

**Issue by frigus02** [BoD/android-contentprovider-generator#86]
When the projection in a query is null, there are multiple columns with name "_id". See https://github.com/BoD/android-contentprovider-generator/issues/40 for more detailed explanation.

The referenced issue was marked as solved, but I experience this problem now. I assume it was introduced again in the commit https://github.com/BoD/android-contentprovider-generator/commit/5456651fede6670b090a618e90ee2225f20bc97e.

**Comment by yargray** [comment]
This problem was fixed absolutely in my pull request https://github.com/BoD/android-contentprovider-generator/pull/88
Any feedback welcome

**Comment by BoD** [comment]
I know this is more than a year late, and I'm sorry.
After thinking about this issue, here are my thoughts:
- When using a `null` projection, the generated SQL is `SELECT * FROM...`
- So if a join is used, there will definitely be several columns named `_id` in the resulting cursor
- One possible way to address this could be to replace `null` by a list of all the columns of all the joined tables, and to alias the `_id` columns (for instance, `company._id as company_id`) - or to omit them (keep only the master table's `_id` column)
- But this seems complicated to do and a bit non intuitive for the user (not really consistent with how `null` projections usually work in Android APIs)
- Therefore my "fix" for now is to keep `null`, and only to put a comment in the README explaining to avoid using `null` projections with joined tables.

One last thought: `null` projections should be avoided in general, not just with joined tables. It is always more efficient to select specific columns.

**Comment by yargray** [comment]
What about my pull request #88 ? It can solve the problem of null projection by default.
