### ISSUE TITLE
Method errors in generated code of v1.9.3

### ISSUE THREAD

**Issue by thvranken** [BoD/android-contentprovider-generator#89]
I get following errors in Android Studio when using the code generated by android-contentprovider-generator 1.9.3, with "TableName" being the provided name for a database table:

error: method orderById(boolean) is already defined in class TableNameSelection
error: method orderById() is already defined in class TableNameSelection
error: method getId() is already defined in class TableNameCursor
error: TableNameCursor is not abstract and does not override abstract method getId() in TableNameModel
error: getId() in TableNameCursor cannot implement getId() in TableNameModel
return type long is not compatible with Integer

**Comment by thvranken** [comment]
Found the problem. These errors occur when you define a column with name "id".

**Comment by BoD** [comment]
Thanks for the report. I guess this should be documented, but indeed, this name is kind of "invalid" :) (because it conflicts with the implicit "_id" column). So closing this issue for now.
