### ISSUE TITLE
Adding support for CursorLoader

### ISSUE THREAD

**Issue by codeversed** [BoD/android-contentprovider-generator#91]
I have been playing around with the idea that the *Object*Selection class would have a method to return a CursorLoader.

Something like this:
```java
public CursorLoader cursorLoader(Context context, String[] projection) {
   return new CursorLoader(context, *Object*Columns.CONTENT_URI, projection, sel(), args(), order()) {
        @Override
        public Cursor loadInBackground() {
             return new *Object*Cursor(super.loadInBackground());
        }
   };
}
```

~~I am personally stuck on how to get the AbstractSelection to come into effect. Would we need a *Object*CursorLoader that extends a *Object*AbstractCursorLoader?~~

It seems that adding that **Edited** code above to the selection class would work well but I am not sure if it is nessessary.

**Comment by eosrei** [comment]
:+1: 

Here is an example creating a CursorLoader using the existing generated code using the [sample project](https://github.com/BoD/android-contentprovider-generator/blob/81a0c651c02076a31ca35f641f2cc82172564216/etc/sample/app/src/org/jraf/androidcontentprovidergenerator/sample/app/SampleActivity.java#L101):
```java
@Override
public Loader<Cursor> onCreateLoader(int id, Bundle args) {
    String[] projection = { PersonColumns._ID, PersonColumns.FIRST_NAME, 
        PersonColumns.LAST_NAME, PersonColumns.AGE };
    final PersonSelection ps = new PersonSelection();
    ps.id(2);

    return new CursorLoader(this, ps.uri(), projection, ps.sel(), ps.args(), ps.order());
}
```

I'm not sure if this is better as a documentation update or a new generated function?

**Comment by crashoverdone** [comment]
Hi, i've been trying to use this generator in my project and i've done everything the right way.
But i'm getting empty cursor on onLoadFinished.
I' m creating the loader as above but no results.
Any help advices?

Thanks in advance

**Comment by BoD** [comment]
Maybe if we can see your code that would help us help you.

**Comment by crashoverdone** [comment]
My code its fine. I'm using a sync service to get the data from a server to populate the DB and i forgot to call the sync adapter in main activity. Now its working fine. Newbie mistake.

And congrats for the nice work. this generator saved me hours of implementation.

Keep up the good work.

Thanks for the quick reply.

**Comment by BoD** [comment]
You're welcome, and thanks 😊

**Comment by BoD** [comment]
In b7be6a0, I added a `getCursorLoader()` method in Selection objects :)
This will be in version 1.10.0.
