### ISSUE TITLE
How to use sum?

### ISSUE THREAD

**Issue by umitems** [BoD/android-contentprovider-generator#94]
I want to use groupBy and sum together

**Comment by BoD** [comment]
There is a `groupBy` method in the `AbstractSelection` class (that all Selection classes extend).

**Comment by umitems** [comment]
Yes I already use group by, its working well.
However, I also want to sum value too.
e.g.

name price
a          3
a          2
b          4

I want 
name price
a          5
b          4

but only GroupBy I got
name price
a          3
b          4

**Comment by BoD** [comment]
I'd have to see your code, but basically you simply need to have "sum(price)" in your selection.
