### ISSUE TITLE
Support available for Batch insert 

### ISSUE THREAD

**Issue by mikkymoto** [BoD/android-contentprovider-generator#95]
Hey I like to check if this this project is still maintained and any support for batch inserts of data

**Comment by BoD** [comment]
This project is maintained yes. 
Batch inserts are supported.

**Comment by mikkymoto** [comment]
From which version it is supported as i use 1.8.3 , will you please give a small code snippet

**Comment by BoD** [comment]
Even though it has always been supported, you should really use the latest version.
As for the batch inserts, you simply need to use either:
- http://developer.android.com/reference/android/content/ContentProvider.html#bulkInsert(android.net.Uri, android.content.ContentValues[])
- http://developer.android.com/reference/android/content/ContentProvider.html#applyBatch(java.util.ArrayList<android.content.ContentProviderOperation>)
