### ISSUE TITLE
To use the tool

### ISSUE THREAD

**Issue by thaopit1992** [BoD/android-contentprovider-generator#98]
Hi, i'm very happy when you created this the tool, but i don't understend input and output when run this tool, can you guide step by tep for me ?

**Comment by BoD** [comment]
Input is the directory where the json files are.
Output is the directory where the code will be generated.

**Comment by thaopit1992** [comment]
yes, you can run the app step by step instructions to get the output?

**Comment by BoD** [comment]
Sorry, I do not understand the question.
