### ISSUE TITLE
Cannot declare a field "ID"

### ISSUE THREAD

**Issue by diwakar-s-maurya** [BoD/android-contentprovider-generator#99]
using version: 1.9.3

I am not able to declare a column with name as "ID" of any data type. If i do, then two functions get created in Cursor file, 
- one for getting the primary key: "public long getId()"
- other for my column: "public String getId()".

Similar thing happens in Selection file with orderById method.

**Comment by BoD** [comment]
I am sorry, this intended - by design.
An `_id` column is automatically created (as per the recommended practice for content providers).
Because of this if you need another id column, you will have to name it differently.
